name: Eumel Discord Bot
version: 0.1
slug: eumel_discord_bot
description: EumelBot as a Homeassistent Plugin 
url: "https://github.com/ToichiKuroba/hassio-eumel-bot"
arch:
  - armhf
  - armv7
  - amd64

advanced: true
host_network: true
options: 
  discord_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
schema:
  discord_token: str
stage: experimental
init: false
